### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by byersiiasa** [fmaussion/salem#130]
(master version)

Got error on import, Python 3, Windows

```
import salem
Traceback (most recent call last):

  File "<ipython-input-3-f947a389823b>", line 1, in <module>
    import salem

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\lib\site-packages\salem\__init__.py", line 60, in <module>
    from salem.datasets import *

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\lib\site-packages\salem\datasets.py", line 45, in <module>
    from salem import utils, gis, wrftools, sio

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\lib\site-packages\salem\utils.py", line 89, in <module>
    memory = Memory(location=hash_cache_dir + '_joblib', verbose=0)

TypeError: __init__() got an unexpected keyword argument 'location'
```

**Comment by fmaussion** [comment]
Hi @byersiiasa , could you try to update joblib and report back? The reason is probably https://github.com/fmaussion/salem/pull/126 , I probably shouldn't have been so eager in changing without taking care of older joblib versions

**Comment by byersiiasa** [comment]
@fmaussion I just updated joblib from 0.11 to 0.13 and that seemed to work fine!
Note that the latest pip release 0.22? was working fine with joblib 0.11
Thanks!
